# NumPy
NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a vast collection of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np

In [2]:
A1 = np.array([1, 2, 3])
print("Array with Rank 1:\n", A1)
result = A1 + 5
print("After adding 5 to each element:\n", result)

Array with Rank 1:
 [1 2 3]
After adding 5 to each element:
 [6 7 8]


In [14]:
# Range 
A2 = np.arange(1, 10, 2)
print(A2)

[1 3 5 7 9]


In [15]:
# linspace
A3 = np.linspace(5, 6, 15)
print(A3)

[5.         5.07142857 5.14285714 5.21428571 5.28571429 5.35714286
 5.42857143 5.5        5.57142857 5.64285714 5.71428571 5.78571429
 5.85714286 5.92857143 6.        ]


In [16]:
# zeros
A4 = np.zeros((3, 3))
print(A4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
A5 = np.ones((2, 3))
print(A5)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
A6 = np.eye(4)
print(A6) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# random
A7 = np.random.rand(2, 3)
print(A7)

[[0.78880602 0.25215554 0.19810909]
 [0.97559176 0.59197697 0.70433143]]


In [20]:
A8 = np.array([1, 2, 3, 4, 5])
print(np.sum(A8))

15


In [26]:
A9 = np.array([[1, 2], [3, 4]])
print(A9)
print(np.mean(A9))

[[1 2]
 [3 4]]
2.5


In [24]:
# concatenate
concatenated_arr = np.concatenate((A9, A9))
concatenated_arr

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [27]:
transposed_arr = A9.transpose()
transposed_arr

array([[1, 3],
       [2, 4]])

In [28]:
arr_min = np.min(A9)
arr_min

1

In [30]:
# max
arr_max = np.max(A9)
arr_max

4

In [29]:
# sum
arr_sum  = np.sum(A9)
arr_sum

10

In [31]:
dot_product = np.dot(A9, A9)
dot_product

array([[ 7, 10],
       [15, 22]])

In [32]:
# absolute
array = np.array([-3, -2, -1, 0, 1, 2, 3])
absolute_array = np.abs(array)
print(absolute_array)

[3 2 1 0 1 2 3]


In [34]:
# sqrt
square_root = np.sqrt(10)
square_root

3.1622776601683795

In [36]:
# exponent
exponential_values = np.exp(50)
exponential_values

5.184705528587072e+21

In [37]:
# percentile
arr = [20, 2, 7, 1, 34]
print("50th percentile of arr:", np.percentile(arr, 50))
print("25th percentile of arr:", np.percentile(arr, 25))
print("75th percentile of arr:", np.percentile(arr, 75))

50th percentile of arr: 7.0
25th percentile of arr: 2.0
75th percentile of arr: 20.0


In [42]:
# division
div = np.divide(25, 15)
div

1.6666666666666667

In [43]:
# subtraction
sub = np.subtract(-24, -5)
sub

-19